cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
# tap 'heroku/brew'
tap 'snyk/tap'
tap 'thoughtbot/formulae'

# Java: install via SDKMAN (https://sdkman.io) or 'brew install --cask temurin'

# install desired scripts
brew 'awscli'
brew 'bazel'
brew 'circleci'
brew 'clojure'
# brew 'emacs'
brew 'fzf'
brew 'lazygit'
brew 'git-standup'
brew 'gh'
# brew 'hugo'
brew 'kubernetes-helm'
brew 'kubectl'
# brew 'leiningen'
brew 'maven'
brew 'minikube'
brew 'neovim'
brew 'node'
brew 'nvm'
brew 'pgweb'
brew 'postgresql'
# brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
# brew 'ruby'
# brew 'ruby-build'
brew 'scala'
brew 'snyk'
brew 'stow'
brew 'tmux'
brew 'tfenv'
brew 'tree'
brew 'vim'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'z'
brew 'zsh'

cask 'the-unarchiver'
cask 'caffeine'
cask 'discord'
cask 'docker'
# cask 'google-chrome'
cask 'google-cloud-sdk'
# cask 'firefox-developer-edition'
cask 'flux'
cask 'iterm2'
cask 'jetbrains-toolbox'
# cask 'keybase'
cask 'miro-formerly-realtimeboard'
cask 'macdown'
cask 'muzzle'
cask 'postman'
cask 'pgadmin4'
cask 'remembear'
cask 'skitch'
cask 'robo-3t'
cask 'slack'
cask 'spotify'
cask 'skype'
cask 'spectacle'
cask 'superduper'
# cask 'telegram-desktop'
# cask 'tunnelblick'
cask 'vlc'
cask 'visual-studio-code'
cask 'whatsapp'

# Fonts
cask 'font-roboto'
cask 'font-fira-code'
cask 'font-jetbrains-mono'
cask 'font-hasklig'
cask 'font-lato'            
cask 'font-roboto-condensed'

# Recommended apps
# cask 'omnifocus'

