"============================================================
"                     ~My vimrc~
"============================================================
"
" Author:       Robert Jones [http://github.com/robert-g-j]
" Source:       https://github.com/robert-g-j/dotfiles
"
"============================================================
"                     ~Mappings~

nnoremap p p`[v`]=

" Easy access to the start of the line
nmap 0 ^<cr>
" Set Leader to be the space-bar
let mapleader = "\<Space>"

" New tab and edit vimrc
nmap <leader>vi :tabedit $MYVIMRC<cr>
" Source (reload) the vimrc
nmap <leader>so :source $MYVIMRC<cr>

" Save file on escaping insert mode
imap <esc> <esc>:w<cr>

"============================================================
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
" alternatively, pass a path where Vundle should install plugins

call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'myusuf3/numbers.vim' "Relative line numbers
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive' "Git wrapper
Plugin 'tpope/vim-sensible' "Universal, agreeable defaults
Plugin 'kien/ctrlp.vim'     "Fuzzy Search
Plugin 'tpope/vim-surround' "parentheses support
Plugin 'altercation/vim-colors-solarized' "easy on the eye 
Plugin 'w0rp/ale'           "async linting
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Plugin 'ascenator/L9', {'name': 'newL9'}
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" 
" Put your non-Plugin stuff after this line
syntax enable
set background=dark
colorscheme solarized
"Use system clipboard.

if has('unnamedplus')
	set clipboard=unnamed,unnamedplus
endif
set t_Co=256              " enable 256-color mode.
set number                " show line numbers
set laststatus=2          " last window always has a statusline
set nohlsearch            " Don't continue to highlight searched phrases.
set incsearch             " But do highlight as you type your search.
set ignorecase            " Make searches case-insensitive.
set ruler                 " Always show info along bottom.
set autoindent            " auto-indent
set tabstop=2             " tab spacing
set softtabstop=2         " unify
set shiftwidth=2          " indent/outdent by 2 columns
set shiftround            " always indent/outdent to the nearest tabstop
set expandtab             " use spaces instead of tabs
set smarttab              " use tabs at the start of a line, spaces elsewhere
"set nowrap                " don't wrap text
